### ISSUE TITLE
Create public voice chat command

### ISSUE THREAD

**Issue by ScoreUnder** [ScoreUnder/canti-bot#1]
`&public` command: like `&private`, except the channel it creates is open by default.

Does not need to interact with the invites system in any special way, and should not create user-limited channels.

**Comment by Brod8362** [comment]
Can they be configured to go into their own category on the server?
Why aren't user limited channels available for public channels?

How is ownership of the channel handled? If the original creator leaves but there's still user(s) in the channel, how is it determined who ownership goes to? Or is the channel disbanded when the creator leaves?

**Comment by ScoreUnder** [comment]
> Can they be configured to go into their own category on the server?

Currently they just go into the same category as the voice channel the user was in when they ran the command.

Do you think I should make this available somehow? Maybe a server-admin-configurable "user channels" category that all these private/public channels get lumped into if it's set?

> Why aren't user limited channels available for public channels?

It would do the same thing as &private: restricting the channel in number only. Maybe I should make it available for both with the same behaviour to avoid confusion.

> How is ownership of the channel handled? If the original creator leaves but there's still user(s) in the channel, how is it determined who ownership goes to? Or is the channel disbanded when the creator leaves?

The owner of the channel is always the one who originally created it, and ownership transfers are not possible (you can however just create an identical channel and bring people there). The channel disbands only when it is empty.

**Comment by ScoreUnder** [comment]
Fixed in #10
